### ISSUE TITLE
lightbox for thumbnails

### ISSUE THREAD

**Issue by mmiat** [paginagmbh/redmine_lightbox2#17]
can I insert lightbox in wiki? thanks

**Comment by tofi86** [comment]
Have you even tried?! This should be working...

**Comment by mmiat** [comment]
I don't know how I can do :)

**Comment by tofi86** [comment]
Follow the installation instructions for the plugin, upload an image to your wiki page, insert normal or as thumbnail and try.

**Comment by mmiat** [comment]
sorry but I can't

I've inserted {{thumbnail(image.jpg)}} but it's a link and it opens image in a new page, not open a lightbox

if I attach image to wiki page I can open a lightbox

thanks

**Comment by tofi86** [comment]
Latest version released a few minutes ago now supports lightbox for thumbnail previews.

**Comment by mmiat** [comment]
I've tried but lightbox doesn't work any more :(
I've reinstalled old version and it's ok

**Comment by tofi86** [comment]
which redmine version do you use?

**Comment by tofi86** [comment]
confirmed for branch `redmine-2.6` and the bug is fixed in new version 0.1.5
Enjoy! :-)

**Comment by mmiat** [comment]
ok, now it works again in issues but still not in wiki, where I simply add:

{{thumbnail(Lighthouse.jpg)}}

maybe I've to specify something?
thanks

**Comment by tofi86** [comment]
Confirmed. Thumbnails are not working in wikis right now.

**Comment by tofi86** [comment]
* Fixed in branch `redmine-2.6` for Redmine 2.6 with commit 75e4db6a2f34d2cf98342f2806068a023d9457ae
* Fixed in branch `master` for Redmine 3 with commit 827863de77b46ff9a2a1005fa111f345fe9d4594

Please try the new versions!
